# version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.huggingface
    # volumes:
    #   - /Users/gyue/Documents/GitHub/fulltclash/resources/config.yaml:/app/resources/config.yaml
    network_mode: host
    ports:
      - "7890:7890"
    environment:
      - TRANSFORMERS_CACHE=/app/models
      - HF_HOME=/app/.huggingface
    user: appuser
    restart: always
    container_name: fulltclash-huggingface
